mod 'boxen', '2.1.0', :github_tarball => 'boxen/puppet-boxen'
mod 'stdlib', '4.0.0', :github_tarball => "puppetlabs/puppetlabs-stdlib"
mod 'ruby', '6.3.4', :github_tarball => 'boxen/puppet-ruby'

mod "gcc",        "1.0.0", :github_tarball => "boxen/puppet-gcc"
mod "homebrew",   "1.1.2", :github_tarball => "boxen/puppet-homebrew"
mod "repository", "2.2.0", :github_tarball => "boxen/puppet-repository"
mod "xquartz",    "1.1.0", :github_tarball => "boxen/puppet-xquartz"
mod "autoconf",   "1.0.0", :github_tarball => "boxen/puppet-autoconf"
mod "openssl",    "1.0.0", :github_tarball => "boxen/puppet-openssl"